[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "python311Packages.pysqlite" # Suporte SQLite ao Python
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmd = "gunicorn app:app"